update_plant:
  name: Update Plant
  description: Update the plant
  fields:
    plant_id:
      name: Plant ID
      description: The id of the plant to update
      required: true
      example: "My Plant"
      selector:
        text:
    last_watered:
      name: Last Watered
      description: Last time the plant was watered
      required: false
      selector:
        datetime: {}
    last_fertilized:
      name: Last Fertilized
      description: Last time the plant was fertilized
      required: false
      selector:
        datetime: {}
    watering_interval:
      name: Watering Interval
      description: The interval between watering
      required: false
      example: 3
      selector:
        number:
          min: 1
          max: 100
          mode: slider
          step: 1
    watering_postponed:
      name: Watering Postponed
      description: The time the watering was postponed
      required: false
      selector:
        number:
          min: 0
          max: 100
          mode: slider
          step: 1
create_plant:
  name: Create Plant
  description: Create a plant
  fields:
    plant_name:
      name: Name
      description: The name of the plant
      required: true
      example: "My Plant"
      selector:
        text:
    last_watered:
      name: Last Watered
      description: Last time the plant was watered
      required: false
      selector:
        datetime: {}
    last_fertilized:
      name: Last Fertilized
      description: Last time the plant was fertilized
      required: false
      selector:
        datetime: {}
    watering_interval:
      name: Watering Interval
      description: The interval between watering
      required: false
      example: 3
      selector:
        number:
          min: 1
          max: 100
          mode: slider
          step: 1
    watering_postponed:
      name: Watering Postponed
      description: The time the watering was postponed
      required: false
      selector:
        number:
          min: 0
          max: 100
          mode: slider
          step: 1
update_days_since_watered:
  name: Update Days Since Watered
  description: Update the days since the plant was watered
delete_plant:
  name: Delete Plant
  description: Delete the plant
  fields:
    plant_id:
      name: Plant ID
      description: The id of the plant to delete
      required: true
      example: "My Plant"
      selector:
        text:
